### ISSUE TITLE
Switch animation on press

### ISSUE THREAD

**Issue by jdrorrer** [thousight/react-native-draggable-switch#9]
I think this is the best/most extensible switch package I've seen for react native, so kudos to you all. There was one issue I ran into - the switch's value only changes when pressing the circle. I think the value should change when pressing the switch anywhere, like it works with RN's default Switch.

I was able to find a workaround, but I think it's something that should be handled by this package - if you disagree, feel free to close this issue. My workaround involves wrapping the Switch in a TouchableOpacity and calling toggle directly on the Switch's ref when onPress occurs.

```
...
import Switch from 'react-native-draggable-switch';
...
handleValueChange = () => {
  const { onValueChange } = this.props;
  const { isOn } = this.state;

  this.setState({ isOn: !isOn }, () => {
    this.switchRef.current.toggle(this.state.isOn);
    onValueChange();
  });
};
...
render() {
  ...
  return (
    <TouchableOpacity onPress={this.handleValueChange}>
      <Switch
        ref={this.switchRef}
        width={50}
        height={30}
        value={this.state.isSwitchOn}
        onValueChange={this.handleValueChange}
      />
    </TouchableOpacity>
  )
}
...
```

**Comment by thousight** [comment]
@jdrorrer Well, first of all, thanks for the compliment, it means a lot. And the main reason why I designed it this way is that I believe the nature of the Switch, in the physical world, should be dragged to change its "value". But I do see it can be more intuitive to simply tap the whole Switch to change the value, depending on how you want the UX to be. I can add a property called onPress() so that you may pass in a setState() to change the isSwitchOn value, but by doing that it may disable the circle dragging and its enlarging animation. Let me know how do you like this idea. If you like it and you need this into the lib fast, feel free to submit a PR for that. If you want me to do it, I will need some time to work on it since I also have my day-to-day priorities. Let me know.

**Comment by jdrorrer** [comment]
@thousight You're welcome! No rush. I posted this issue because I had to implement a workaround and also because with the workaround, there was a delay (maybe 1 second) before the switch would animate to the other side. I was able to get around that using setTimeout, though, and it works as expected now. Here is the full working workaround in case others using this library run into the same issue:

```
...
import Switch from 'react-native-draggable-switch';
...
constructor(props) {
  super(props);
  this.animationDelay = null;
  this.switchRef = React.createRef();
}

componentWillUnmount() {
  clearTimeout(this.animationDelay);
}

handleValueChange = () => {
  const { onValueChange } = this.props;
  const { isOn } = this.state;

  this.setState({ isOn: !isOn }, () => {
    this.animationDelay = setTimeout(() => {
      this.switchRef.current.toggle(this.state.isOn);
      onValueChange();
    }, 0);
  });
};
...
render() {
  ...
  return (
    <TouchableOpacity onPress={this.handleValueChange}>
      <Switch
        ref={this.switchRef}
        width={50}
        height={30}
        value={this.state.isSwitchOn}
        onValueChange={this.handleValueChange}
      />
    </TouchableOpacity>
  )
}
...
```

**Comment by jdrorrer** [comment]
🎉 @thousight awesome!
